### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by xPMo** [xPMo/zsh-vim-system-clipboard#3]
@kutsan @damianrath The two of you were kind enough to star this repo, so I figure I'd ask you about how things should be named:

**Plugin name**: currently `zsh-vim-system-clipboard`, but that's pretty long... I want to keep the `zsh-` prefix though. It may be too late at this point, though.

**Arrays name**: In PR #1 I am using arrays to hold the copy/paste handlers to allow users to extend with their own custom clipboards. On that branch, you can add/override a copy handler with:

```zsh
_system_copy_handlers[/]=">> $HOME/.scraps"
_system_copy_handlers[,]='tmux load-buffer -b zsh -'
_system_paste_handlers[,]='tmux paste-buffer -b zsh'
```
(With this, now `"/y<vi-motion>` will append the yanked text to ~/.scraps, and `",` now gives access to the tmux buffer labeled "zsh".)

But, again, the array names I'm using are pretty long. Any suggestions are appreciated.

**Comment by damianrath** [comment]
Well, IMHO and in the spirit of having the name descriptive I would use 'zsh-vim-sys-clipb' as file/dir names, but keep the name of the project zsh-vim-system-clipboard.

It's not too long when referring to it as a project.

**Comment by xPMo** [comment]
After a few days to think about it, I think `zvsc_copy_handlers` and `zvsc_paste_handlers`, (zvsc as an acronym for zsh-vim-system-clipboard), and keep the `zvsc_` prefix for any further variables I might use.  I believe this is common practice for most plugins. (e.g.: pure, zplugin, f-s-h, fzf).

**Comment by kutsan** [comment]
First of all, I'm so sorry that took quiet a bit days to actually find a time period to answer your questions. I've been busy nowadays with my in-real-life things.

> The two of you were kind enough to star this repo

This's really good hear, thanks!

> currently `zsh-vim-system-clipboard`, but that's pretty long... I want to keep the zsh- prefix though. It may be too late at this point, though.

In my opinion, `zsh` prefix is kind of mandatory, at least it suits with its ecosystem well. For the other thing, I actually don't think it's long as @damianrath says, it declares what it does in the name.
Or maybe you should go with a unique name something like `zsh-vimmy-clippy`?

> the array names I'm using are pretty long. Any suggestions are appreciated.

As common practices you should make all uppercase prefixed with a full project name like,

```sh
ZSH_VIM_SYSTEM_CLIPBOARD_COPY_HANDLERS[/]=">> $HOME/.scraps"
```

Yes, it's long but in a first glance it tells you that it's a variable about a plugin and configurable by user. In the other hand, `zvsc_copy_handlers` means nothing to me. It's like an exposed internal variable about ZLE's own mechanism. Also, typing `typeset` on command-line lists all variables FYI.

**Comment by xPMo** [comment]
Really, if I were to give this project a better name, I'd call it something like "zsh-vi-registers-plus" or "zsh-evil-registers". Especially with #4 on the way, and the potential for more editor sync support (vim, spacemacs maybe?).

I'm too narrowly-focused when writing it, so the longer variables didn't feel right to me. I think I'll take your suggestion for now.

P.S.: I am really liking the "evil" idea:

>  `EVIL_COPY_HANDLERS`, `EVIL_PASTE_HANDLERS`, `EVIL_SYNC_EDITOR`

It has a nice look to it. Don't be surprised if I fork the project into xPMo/zsh-evil-registers.
